### ISSUE TITLE
Instagram Hashtags

### ISSUE THREAD

**Issue by Linkerss** [stefansundin/rssbox#46] opened 2020-12-03 11:04 UTC
Hey Stefan, Any chance you allow Instagram Hashtags on your App?

I don't mind paying subscription fee if that's requirement,

Thank you

**Comment by stefansundin** [comment] 2022-08-29 16:15
Duplicate of https://github.com/stefansundin/rssbox/issues/27.

**Closed by stefansundin** 2022-08-29 16:15 UTC
